# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 152dc4fff3a330cb92788dd26279912ce678937e283b85234f40ea0328cd4914ac4f5ee56ae4d4ae59e919bae205db9d9f7e91676c9140e0083251628c85315c

test:
  secret_key_base: 01c75a34393e69fcbb02bcedf348f5af9d9e585833d07e60a1bc9708413bf3573e393ac231bba7cf094add4c749732c3f5c88f70d3c069c776e31872ca2c0f7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
